// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmbkgqmsjwtevipkbvoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptYmtncW1zand0ZXZpcGtidm96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3Nzg4NDgsImV4cCI6MjA4ODM1NDg0OH0.bjxJ1sFF7UQ4DphziemPMu6ahu9aFO4h0wAII89cphw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});